version: '3'

services:
  database-service:
    image: mysql:latest
    container_name: database-service
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: pg_aftersales_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - webnet
      - pg_microservice

  sales:
    image: magicfinger/pg_new:v4
    expose:
      - "8081"
    ports:
      - 8081:8081
    depends_on:
        - database-service
    networks:
      - webnet
      - pg_microservice




networks:
  - webnet
  - pg_microservice